# .github/workflows/deploy.yml
name: Deploy to GitHub Pages

on: 
  push:
    branches:
      - main  # Executa a ação em qualquer push na branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure GitHub Pages to use branch 'main' and path 'root'
        run: |
          mkdir -p out/
          touch out/test.txt
          echo "${{ secrets.KEY1 }}" >> out/test.txt

      - name: Publish spec
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: "out/"
          commit_user_name: veecode-bot
          commit_user_email: github-admin@vee.codes
          commit_author: veecode-bot<github-admin@vee.codes>
          commit_message: "Publish api"
          push_options: '--force'